### PR TITLE
Added 3.10 support and removed 3.7 support

### LINKED ISSUE #140: Unable to install pantab via pip: pantab/src/pantab.c:6:10: fatal error: cffi.h: No such file or directory
**Issue**: Using Fedora 35, Python 3.10.0, and pip 21.3.1, I am no longer able to install pantab via pip

**Description**:  I've been using pantab for awhile on Fedora/RHEL/Ubuntu, however I encountered an issue today installing pantab via pip (initially using poetry).  When poetry failed, I attempted the installation directly using pip, and when that failed I also attempted a broader sudo installation to ensure that it wasn't a file permissions issue.  The installation had worked without issue previously, though I cannot verify if the upgrade to Fedora 35 (and Python 3.10.0) was the definitely change giving rise to the issue as I haven't installed it in a project recently prior to upgrading.

**Replication**:  See the above installation context for replication purposes, running the command(s):

`python3 -m pip install --user --upgrade pantab`
`pip3 install --upgrade pantab`

**Relevant log(s)**:
```
  creating build/temp.linux-x86_64-3.10/pantab/src
  gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DNPY_NO_DEPRECATED_API=0 -I/tmp/pip-build-env-bshf6e1p/overlay/lib64/python3.10/site-packages/numpy/core/include -I/usr/include/python3.10 -c pantab/src/numpy_datetime.c -o build/temp.linux-x86_64-3.10/pantab/src/numpy_datetime.o -Wextra -Werror
  gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DNPY_NO_DEPRECATED_API=0 -I/tmp/pip-build-env-bshf6e1p/overlay/lib64/python3.10/site-packages/numpy/core/include -I/usr/include/python3.10 -c pantab/src/pantab.c -o build/temp.linux-x86_64-3.10/pantab/src/pantab.o -Wextra -Werror
  pantab/src/pantab.c:6:10: fatal error: cffi.h: No such file or directory
      6 | #include "cffi.h"
        |          ^~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for pantab

```

***Full Log(s)**: 

```
[josgood@localhost vdm-checks]$ python3 -m pip install --user --upgrade pantab
Collecting pantab
  Using cached pantab-2.1.0.tar.gz (28 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pandas
  Using cached pandas-1.3.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.5 MB)
Collecting tableauhyperapi
  Using cached tableauhyperapi-0.0.13980-py3-none-manylinux2014_x86_64.whl (46.7 MB)
Collecting numpy
  Using cached numpy-1.22.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/lib/python3.10/site-packages (from pandas->pantab) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /usr/lib/python3.10/site-packages (from pandas->pantab) (2021.3)
Requirement already satisfied: cffi!=1.14.3,<2,>=1.12.2 in /usr/lib64/python3.10/site-packages (from tableauhyperapi->pantab) (1.14.6)
Requirement already satisfied: pycparser in /usr/lib/python3.10/site-packages (from cffi!=1.14.3,<2,>=1.12.2->tableauhyperapi->pantab) (2.20)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.10/site-packages (from python-dateutil>=2.7.3->pandas->pantab) (1.16.0)
Requirement already satisfied: ply==3.11 in /usr/lib/python3.10/site-packages (from pycparser->cffi!=1.14.3,<2,>=1.12.2->tableauhyperapi->pantab) (3.11)
Building wheels for collected packages: pantab
  Building wheel for pantab (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/josgood/.local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpno23yugz
       cwd: /tmp/pip-install-d40nu7kx/pantab_c1b9219babb9402c9676833152a37b41
  Complete output (38 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.10
  creating build/lib.linux-x86_64-3.10/pantab
  copying pantab/_writer.py -> build/lib.linux-x86_64-3.10/pantab
  copying pantab/_types.py -> build/lib.linux-x86_64-3.10/pantab
  copying pantab/_tester.py -> build/lib.linux-x86_64-3.10/pantab
  copying pantab/_reader.py -> build/lib.linux-x86_64-3.10/pantab
  copying pantab/_hyper_util.py -> build/lib.linux-x86_64-3.10/pantab
  copying pantab/_compat.py -> build/lib.linux-x86_64-3.10/pantab
  copying pantab/__init__.py -> build/lib.linux-x86_64-3.10/pantab
  creating build/lib.linux-x86_64-3.10/benchmarks
  copying benchmarks/custom.py -> build/lib.linux-x86_64-3.10/benchmarks
  copying benchmarks/benchmarks.py -> build/lib.linux-x86_64-3.10/benchmarks
  copying benchmarks/__init__.py -> build/lib.linux-x86_64-3.10/benchmarks
  creating build/lib.linux-x86_64-3.10/pantab/tests
  copying pantab/tests/test_writer.py -> build/lib.linux-x86_64-3.10/pantab/tests
  copying pantab/tests/test_roundtrip.py -> build/lib.linux-x86_64-3.10/pantab/tests
  copying pantab/tests/test_reader.py -> build/lib.linux-x86_64-3.10/pantab/tests
  copying pantab/tests/conftest.py -> build/lib.linux-x86_64-3.10/pantab/tests
  copying pantab/tests/__init__.py -> build/lib.linux-x86_64-3.10/pantab/tests
  creating build/lib.linux-x86_64-3.10/pantab/tests/data
  copying pantab/tests/data/non_pantab_writeable.hyper -> build/lib.linux-x86_64-3.10/pantab/tests/data
  copying pantab/tests/data/geography.hyper -> build/lib.linux-x86_64-3.10/pantab/tests/data
  copying pantab/tests/data/dates.hyper -> build/lib.linux-x86_64-3.10/pantab/tests/data
  running build_ext
  creating build/temp.linux-x86_64-3.10
  creating build/temp.linux-x86_64-3.10/pantab
  creating build/temp.linux-x86_64-3.10/pantab/src
  gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DNPY_NO_DEPRECATED_API=0 -I/tmp/pip-build-env-d1ov3ce6/overlay/lib64/python3.10/site-packages/numpy/core/include -I/usr/include/python3.10 -c pantab/src/numpy_datetime.c -o build/temp.linux-x86_64-3.10/pantab/src/numpy_datetime.o -Wextra -Werror
  gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DNPY_NO_DEPRECATED_API=0 -I/tmp/pip-build-env-d1ov3ce6/overlay/lib64/python3.10/site-packages/numpy/core/include -I/usr/include/python3.10 -c pantab/src/pantab.c -o build/temp.linux-x86_64-3.10/pantab/src/pantab.o -Wextra -Werror
  pantab/src/pantab.c:6:10: fatal error: cffi.h: No such file or directory
      6 | #include "cffi.h"
        |          ^~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for pantab
Failed to build pantab
ERROR: Could not build wheels for pantab, which is required to install pyproject.toml-based projects

```

### PR DESCRIPTION
**Pull request by jrosgood**
closes #140

### CODE REVIEW

**Comment by WillAyd** [comment]
I think we need to remove the "pandas < 1.3" from the CI jobs for the failing windows job

https://github.com/innobi/pantab/blob/b89ea8bdf7804c77b806f977be90e5cd4d7defcd/.github/workflows/pythonpackage.yml#L120

**Comment by jrosgood** [comment]
Should the entire pandas12 tests be removed or just 3.10?  I assume they were included for backward compatibility checks but 1.2 support for newer Python versions is likely to disappear over time, and it's similarly unlikely that Python >3.9 users will be working with a 1.2.x version of Pandas.  

I'm happy to quickly remove either the entire set of 1.2 tests or just the 3.10 from the 1.2 matrices as necessary

**Comment by WillAyd** [comment]
Good point. Can just remove the 3.10 from the windows matrix for pandas12 testing

**Comment by WillAyd** [comment]
@jrosgood thanks for the PR! I've posted the 3.10 wheels to pypi so give it a shot now and let me know if things aren't better

**Comment by jrosgood** [comment]
@WillAyd Thanks for letting me jump in and contribute!  It worked perfectly

```(base) [josgood@localhost pantab]$ python3 -m pip install pantab
Defaulting to user installation because normal site-packages is not writeable
Collecting pantab
  Downloading pantab-2.1.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (407 kB)
     |████████████████████████████████| 407 kB 3.7 MB/s            
<snip>
Successfully installed pantab-2.1.0
```
